type Song = {
    cover: string;
    title: string;
    artist: string;
    album: string;
    time: string;
    lyrics?: string[];
};

export const songPaths: string[] = [
    'Mark%20Ronson/Uptown%20Funk%20(feat.%20Bruno%20Mars)',
    'LMFAO/Party%20Rock%20Anthem',
    'Ed%20Sheeran/Shape%20of%20You',
    'The%20Chainsmokers/Closer',
    'Maroon%205/Girls%20Like%20You%20(Cardi%20B%20Version)',
    'Rihanna/We%20Found%20Love%20(Album%20Version)',
    'Lil%20Nas%20X/Old%20Town%20Road',
    'Gotye/Somebody%20That%20I%20Used%20To%20Know',
    '',
    'Adele/Rolling%20in%20the%20Deep',
    'Post%20Malone/Sunflower%20(Spider-Man:%20Into%20the%20Spider-Verse)',
    'Halsey/Without%20Me',
    'Carly%20Rae%20Jepsen/Call%20Me%20Maybe',
    'Robin%20Thicke/Blurred%20Lines',
    'Ed%20Sheeran/Perfect',
    'Travis%20Scott/SICKO%20MODE',
    'All%20About%20That%20Bass',
    'Lorde/Royals',
    `Drake/God's%20Plan`,
    'Maroon%205/Moves%20Like%20Jagger',
    'Pharrell%20Williams/Happy%20(From%20%22Despicable%20Me%202%22)',
    'Bruno%20Mars/Just%20the%20Way%20You%20Are',
    'Post%20Malone/rockstar',
    'Kesha/TiK%20ToK',
    'Wiz%20Khalifa/See%20You%20Again%20(feat.%20Charlie%20Puth)',
    'Katy%20Perry/Dark%20Horse',
    '',
    'Maroon%205/One%20More%20Night',
    'fun./We%20Are%20Young%20(feat.%20Janelle%20Mon%C3%A1e)',
    `Bruno%20Mars/That's%20What%20I%20Like`,
    '',
    'John%20Legend/All%20of%20Me',
    '',
    'Taylor%20Swift/Shake%20It%20Off',
    'Drake/One%20Dance',
    'Imagine%20Dragons/Radioactive',
    'LMFAO/Sexy%20And%20I%20Know%20It',
    'Adele/Someone%20Like%20You',
    'OneRepublic/Counting%20Stars',
    '',
    'Fetty%20Wap/Trap%20Queen',
    'Justin%20Bieber/Love%20Yourself',
    'Katy%20Perry/Firework',
    'Pitbull/Give%20Me%20Everything%20(feat.%20Nayer)',
    'Bruno%20Mars/Locked%20out%20of%20Heaven',
    'Eminem/Love%20The%20Way%20You%20Lie',
    'Ed%20Sheeran/Thinking%20out%20Loud',
    'Justin%20Bieber/Sorry',
    'Katy%20Perry/California%20Gurls',
    'Taio%20Cruz/Dynamite',

]

export const songs: Song[] = [
    {
        cover: "/UptownFunk.png",
        title: "Uptown Funk",
        artist: "Mark Ronson (feat. Bruno Mars)",
        album: "Uptown Special",
        time: "4:30",
        lyrics: [
            "This hit, that ice cold",
            "Michelle Pfeiffer, that white gold",
            "This one for them hood girls",
            "Them good girls, straight masterpieces",
            "Stylin', wilin', livin' it up in the city",
            "Got Chucks on with Saint Laurent",
            "Gotta kiss myself, I'm so pretty",
            "I'm too hot (Hot damn)",
            "Uh, call the police and the fireman",
            "I'm too hot (Hot damn)",
            "Make a dragon wanna retire, man",
            "I'm too hot (Hot damn)",
            "Say my name, you know who I am",
            "I'm too hot (Hot damn)",
            "And my band 'bout that money, break it down",
            "Girls hit your hallelujah (Woo)",
            "Girls hit your hallelujah (Woo)",
            "Girls hit your hallelujah (Woo)",
            "'Cause uptown funk gon' give it to you (Woo)",
            "'Cause uptown funk gon' give it to you",
            "Saturday night and we in the spot",
            "Don't believe me, just watch, come on",
            "Doh-doh-doh, doh-doh-doh, doh-doh (Ya)",
            "Don't believe me, just watch, uh",
            "Doh-doh-doh, doh-doh-doh, doh-doh (Ya)",
            "Don't believe me, just watch, uh",
            "Don't believe me, just watch, uh",
            "Don't believe me, just watch",
            "Don't believe me, just watch",
            "Hey, hey, hey, oh",
            "Stop, wait a minute",
            "Fill my cup, put some liquor in it",
            "Take a sip, sign the check",
            "Julio, get the stretch",
            "Ride to Harlem, Hollywood, Jackson, Mississippi",
            "If we show up, we gon' show out",
            "Smoother than a fresh jar of Skippy",
            "I'm too hot (Hot damn)",
            "Call the police and the fireman",
            "I'm too hot (Hot damn)",
            "Make a dragon wanna retire, man",
            "I'm too hot (Too hot, hot damn, hot damn)",
            "Bitch, say my name, you know who I am",
            "I'm too hot (Hot damn)",
            "Uh, and my band 'bout that money, break it down",
            "Girls hit your hallelujah (Woo)",
            "Girls hit your hallelujah (Woo)",
            "Girls hit your hallelujah (Woo)",
            "'Cause uptown funk gon' give it to you (Woo)",
            "'Cause uptown funk gon' give it to you",
            "Saturday night and we in the spot",
            "Don't believe me, just watch, come on",
            "Doh-doh-doh, doh-doh-doh, doh-doh (Ya)",
            "Don't believe me, just watch, uh",
            "Doh-doh-doh, doh-doh-doh, doh-doh (Ya)",
            "Don't believe me, just watch, uh",
            "Don't believe me, just watch, uh",
            "Don't believe me, just watch",
            "Don't believe me, just watch",
            "Hey, hey, hey, oh"
        ]
    },
    {
        cover: '/PartyRockAnthem.png',
        title: 'Party Rock Anthem',
        artist: 'LMFAO',
        album: 'Sorry for Party Rocking',
        time: '4:22',
        lyrics: [
            "Party rock is in the house tonight",
            "Everybody just have a good time (yeah)",
            "And we gon' make you lose your mind (woo)",
            "Everybody just have a good time (clap)",
            "Party rock is in the house tonight",
            "Everybody just have a good time (I can feel it, baby)",
            "And we gon' make you lose your mind (yeah)",
            "We just wanna see you",
            "Shake that",
            "In the club, party rock",
            "Looking for your girl? She on my jock, huh",
            "Non-stop when we in the spot",
            "Booty moving weight like she on the block (woo)",
            "Where the drank? I gots to know",
            "Tight jeans, tattoo, 'cause I'm rock and roll",
            "Half-black, half-white, domino",
            "Gainin' money, Oprah dough",
            "Yo, I'm running through these hoes like Drano",
            "I got that devilish flow, Rock and Roll, no halo, we party rock",
            "Yeah, that's the crew that I'm reppin'",
            "On the rise to the top, no Led in our Zeppelin (hey)",
            "Party rock is in the house tonight",
            "Everybody just have a good time (yeah)",
            "And we gon' make you lose your mind",
            "Everybody just have a good time (let's go)",
            "Party rock is in the house tonight",
            "Everybody just have a good time (I can feel it, babe)",
            "And we gon' make you lose your mind",
            "We just wanna see you",
            "Shake that",
            "Every day I'm shufflin'",
            "Shufflin', shufflin'",
            "Step up fast and be the first girl to make me throw this cash",
            "We gettin' money don't be mad, now stop, hatin' is bad",
            "One more shot for us, another round",
            "Please fill up my cup, don't mess around",
            "We just wanna see, you shake it now",
            "Now you home with me, you're naked now",
            "Get up, get down, put your hands up to the sound",
            "Get up, get down, put your hands up to the sound",
            "Get up, get down, put your hands up to the sound (woo)",
            "Put your hands up to the sound",
            "Put your hands up to the sound (let's go)",
            "Get up, get up, get up, get up",
            "Get up, get up, get up, get up",
            "Get up, put your hands up to the sound, to the sound (woo)",
            "Put your hands up, put your hands up, put your hands up, put your hands up",
            "Party rock is in the house tonight (put your hands up)",
            "Everybody just have a good time (put your hands up)",
            "And we gon' make you lose your mind (put your hands up)",
            "Everybody just have a good, good, good time",
            "Whoa (put your hands up)",
            "Whoa (I can feel it, babe)",
            "Whoa (put your hands up)",
            "Whoa (put your hands up)",
            "Shake that",
            "Every day I'm shufflin'",
            "Put your, put your (hands up)",
            "Put your, put your (yeah)",
            "Put your, put your (woo)",
            "(Hands up)",
            "Put your, put your (hands up)",
            "Put your hands up",
            "Your hands up",
            "Put your hands up"
        ]
    },
    {
        cover: '/ShapeOfYou.png',
        title: 'Shape of You',
        artist: 'Ed Sheeran',
        album: 'Divide',
        time: '3:54',
        lyrics: [
            "A club isn't the best place to find a lover",
            "So the bar is where I go (Mm)",
            "Me and my friends at the table doin' shots",
            "Drinkin' fast and then we talk slow (Mm)",
            "And you come over and start up a conversation with just me",
            "And trust me, I'll give it a chance now (Mm)",
            "Take my hand, stop, put Van the Man on the jukebox",
            "And then we start to dance and now I'm singin' like",
            "Girl, you know I want your love",
            "Your love was handmade for somebody like me",
            "Well, come on now, follow my lead",
            "I may be crazy, don't mind me",
            "Say, 'Boy, let's not talk too much'",
            "Grab on my waist and put that body on me",
            "Well, come on now, follow my lead",
            "Come, come on now, follow my lead, mm",
            "I'm in love with the shape of you",
            "We push and pull like a magnet do",
            "Although my heart is fallin' too",
            "I'm in love with your body",
            "And last night, you were in my room",
            "And now my bed sheets smell like you",
            "Every day, discoverin' somethin' brand new",
            "Well, I'm in love with your body",
            "Oh, I, oh, I, oh, I, oh, I",
            "Well, I'm in love with your body",
            "Oh, I, oh, I, oh, I, oh, I",
            "Well, I'm in love with your body",
            "Oh, I, oh, I, oh, I, oh, I",
            "Well, I'm in love with your body",
            "Every day, discoverin' somethin' brand new",
            "I'm in love with the shape of you",
            "One week in, we let the story begin",
            "We're goin' out on our first date (Mm)",
            "You and me are thrifty, so go all-you-can-eat",
            "Fill up your bag and I fill up a plate (Mm)",
            "We talk for hours and hours about the sweet and the sour",
            "And how your family is doin' okay (Mm)",
            "And leave and get in a taxi, and kiss in the back seat",
            "Tell the driver make the radio play and I'm singin' like"
        ]
    },
    {
        cover: '/Closer.png',
        title: 'Closer',
        artist: 'The Chainsmokers (feat. Halsey)',
        album: 'Collage',
        time: '4:06',
        lyrics: [
            "Hey, I was doing just fine before I met you",
            "I drink too much and that's an issue, but I'm okay",
            "Hey, you tell your friends it was nice to meet them",
            "But I hope I never see them again",
            "I know it breaks your heart",
            "Moved to the city in a broke-down car, and",
            "Four years, no calls",
            "Now you're looking pretty in a hotel bar",
            "And I, I, I, I, I can't stop",
            "No, I, I, I, I, I can't stop",
            "So, baby, pull me closer",
            "In the back seat of your Rover",
            "That I know you can't afford",
            "Bite that tattoo on your shoulder",
            "Pull the sheets right off the corner",
            "Of that mattress that you stole",
            "From your roommate back in Boulder",
            "We ain't ever getting older",
            "We ain't ever getting older",
            "We ain't ever getting older",
            "You look as good as the day I met you",
            "I forget just why I left you, I was insane",
            "Stay and play that Blink-182 song",
            "That we beat to death in Tucson, okay",
            "I know it breaks your heart",
            "Moved to the city in a broke-down car, and",
            "Four years, no call",
            "Now I'm looking pretty in a hotel bar",
            "And I, I, I, I, I can't stop",
            "No, I, I, I, I, I can't stop",
            "So, baby, pull me closer",
            "In the back seat of your Rover",
            "That I know you can't afford",
            "Bite that tattoo on your shoulder",
            "Pull the sheets right off the corner",
            "Of that mattress that you stole",
            "From your roommate back in Boulder",
            "We ain't ever getting older",
            "We ain't ever getting older",
            "We ain't ever getting older"
        ]
    },
    {
        cover: '/GirlsLikeYou.png',
        title: 'Girls Like You',
        artist: 'Maroon 5 (feat. Cardi B)',
        album: 'Red Pill Blues',
        time: '3:55',
        lyrics: []
    },
    {
        cover: '/WeFoundLove.png',
        title: 'We Found Love',
        artist: 'Rihanna (feat. Calvin Harris)',
        album: 'Talk That Talk',
        time: '3:35',
        lyrics: []
    },
    {
        cover: '/OldTownRoad.png',
        title: 'Old Town Road',
        artist: 'Lil Nas X (feat. Billy Ray Cyrus)',
        album: '7 EP',
        time: '2:37',
        lyrics: []
    },
    {
        cover: '/SomebodyThatIUsedToKnow.png',
        title: 'Somebody That I Used To Know',
        artist: 'Gotye (feat. Kimbra)',
        album: 'Making Mirrors',
        time: '4:04',
        lyrics: []
    },
    {
        cover: '/Despacito.png',
        title: 'Despacito',
        artist: 'Luis Fonsi & Daddy Yankee (feat. Justin Bieber)',
        album: 'Despacito – Single',
        time: '3:48',
        lyrics: []
    },
    {
        cover: '/RollingInTheDeep.png',
        title: 'Rolling in the Deep',
        artist: 'Adele',
        album: '21',
        time: '3:48',
        lyrics: []
    },
    {
        cover: '/Sunflower.png',
        title: 'Sunflower',
        artist: 'Post Malone & Swae Lee',
        album: 'Spider-Man: Into the Spider-Verse',
        time: '2:38',
        lyrics: []
    },
    {
        cover: '/WithoutMe.png',
        title: 'Without Me',
        artist: 'Halsey',
        album: 'Manic',
        time: '3:21',
        lyrics: []
    },
    {
        cover: '/CallMeMaybe.png',
        title: 'Call Me Maybe',
        artist: 'Carly Rae Jepsen',
        album: 'Kiss',
        time: '3:13',
        lyrics: []
    },
    {
        cover: '/BlurredLines.png',
        title: 'Blurred Lines',
        artist: 'Robin Thicke (feat. T.I. & Pharrell Williams)',
        album: 'Blurred Lines',
        time: '4:23',
        lyrics: []
    },
    {
        cover: '/Perfect.png',
        title: 'Perfect',
        artist: 'Ed Sheeran',
        album: 'Divide',
        time: '4:23',
        lyrics: []
    },
    {
        cover: '/SickoMode.png',
        title: 'SICKO MODE',
        artist: 'Travis Scott',
        album: 'ASTROWORLD',
        time: '5:12',
        lyrics: []
    },
    {
        cover: '/AllAboutThatBass.png',
        title: 'All About That Bass',
        artist: 'Meghan Trainor',
        album: 'Title',
        time: '3:07',
        lyrics: []
    },
    {
        cover: '/Royals.png',
        title: 'Royals',
        artist: 'Lorde',
        album: 'Pure Heroine',
        time: '3:10',
        lyrics: []
    },
    {
        cover: '/GodsPlan.png',
        title: 'God’s Plan',
        artist: 'Drake',
        album: 'Scorpion',
        time: '3:18',
        lyrics: []
    },
    {
        cover: '/MovesLikeJagger.png',
        title: 'Moves Like Jagger',
        artist: 'Maroon 5 (feat. Christina Aguilera)',
        album: 'Hands All Over',
        time: '3:21',
        lyrics: []
    },
    {
        cover: '/Happy.png',
        title: 'Happy',
        artist: 'Pharrell Williams',
        album: 'G I R L',
        time: '3:52',
        lyrics: []
    },
    {
        cover: '/JustTheWayYouAre.png',
        title: 'Just the Way You Are',
        artist: 'Bruno Mars',
        album: 'Doo-Wops & Hooligans',
        time: '3:40',
        lyrics: []
    },
    {
        cover: '/Rockstar.png',
        title: 'rockstar',
        artist: 'Post Malone (feat. 21 Savage)',
        album: 'beerbongs & bentleys',
        time: '3:38',
        lyrics: []
    },
    {
        cover: '/TiKToK.png',
        title: 'TiK ToK',
        artist: 'Kesha',
        album: 'Animal',
        time: '3:19',
        lyrics: []
    },
    {
        cover: '/SeeYouAgain.png',
        title: 'See You Again',
        artist: 'Wiz Khalifa (feat. Charlie Puth)',
        album: 'See You Again – Single',
        time: '3:49',
        lyrics: []
    },
    {
        cover: '/DarkHorse.png',
        title: 'Dark Horse',
        artist: 'Katy Perry (feat. Juicy J)',
        album: 'PRISM',
        time: '3:35',
        lyrics: []
    },
    {
        cover: '/ThriftShop.png',
        title: 'Thrift Shop',
        artist: 'Macklemore & Ryan Lewis (feat. Wanz)',
        album: 'The Heist',
        time: '3:55',
        lyrics: []
    },
    {
        cover: '/OneMoreNight.png',
        title: 'One More Night',
        artist: 'Maroon 5',
        album: 'Overexposed',
        time: '3:39',
        lyrics: []
    },
    {
        cover: '/WeAreYoung.png',
        title: 'We Are Young',
        artist: 'fun. (feat. Janelle Monáe)',
        album: 'Some Nights',
        time: '4:10',
        lyrics: []
    },
    {
        cover: '/ThatsWhatILike.png',
        title: 'That’s What I Like',
        artist: 'Bruno Mars',
        album: '24K Magic',
        time: '3:26',
        lyrics: []
    },
    {
        cover: '/TheHills.png',
        title: 'The Hills',
        artist: 'The Weeknd',
        album: 'Beauty Behind The Madness',
        time: '4:02',
        lyrics: []
    },
    {
        cover: '/AllOfMe.png',
        title: 'All of Me',
        artist: 'John Legend',
        album: 'Love In The Future',
        time: '4:29',
        lyrics: []
    },
    {
        cover: '/Happier.png',
        title: 'Happier',
        artist: 'Marshmello & Bastille',
        album: 'Happier – Single',
        time: '3:34',
        lyrics: []
    },
    {
        cover: '/ShakeItOff.png',
        title: 'Shake It Off',
        artist: 'Taylor Swift',
        album: '1989',
        time: '3:39',
        lyrics: []
    },
    {
        cover: '/OneDance.png',
        title: 'One Dance',
        artist: 'Drake (feat. Wizkid & Kyla)',
        album: 'Views',
        time: '2:53',
        lyrics: []
    },
    {
        cover: '/Radioactive.png',
        title: 'Radioactive',
        artist: 'Imagine Dragons',
        album: 'Night Visions',
        time: '3:06',
        lyrics: []
    },
    {
        cover: '/SexyAndIKnowIt.png',
        title: 'Sexy And I Know It',
        artist: 'LMFAO',
        album: 'Sorry For Party Rocking',
        time: '3:19',
        lyrics: []
    },
    {
        cover: '/SomeoneLikeYou.png',
        title: 'Someone Like You',
        artist: 'Adele',
        album: '21',
        time: '4:45',
        lyrics: []
    },
    {
        cover: '/CountingStars.png',
        title: 'Counting Stars',
        artist: 'OneRepublic',
        album: 'Native',
        time: '4:17',
        lyrics: []
    },
    {
        cover: '/ET.png',
        title: 'E.T.',
        artist: 'Katy Perry (feat. Kanye West)',
        album: 'Teenage Dream',
        time: '3:26',
        lyrics: []
    },
    {
        cover: '/TrapQueen.png',
        title: 'Trap Queen',
        artist: 'Fetty Wap',
        album: 'Fetty Wap',
        time: '3:42',
        lyrics: []
    },
    {
        cover: '/LoveYourself.png',
        title: 'Love Yourself',
        artist: 'Justin Bieber',
        album: 'Purpose',
        time: '3:53',
        lyrics: []
    },
    {
        cover: '/Firework.png',
        title: 'Firework',
        artist: 'Katy Perry',
        album: 'Teenage Dream',
        time: '3:47',
        lyrics: []
    },
    {
        cover: '/GiveMeEverything.png',
        title: 'Give Me Everything',
        artist: 'Pitbull (feat. AFROJACK, Ne-Yo, & Nayer)',
        album: 'Planet Pit',
        time: '4:12',
        lyrics: []
    },
    {
        cover: '/LockedOutOfHeaven.png',
        title: 'Locked out of Heaven',
        artist: 'Bruno Mars',
        album: 'Unorthodox Jukebox',
        time: '3:53',
        lyrics: []
    },
    {
        cover: '/LoveTheWayYouLie.png',
        title: 'Love The Way You Lie',
        artist: 'Eminem (feat. Rihanna)',
        album: 'Recovery',
        time: '4:23',
        lyrics: []
    },
    {
        cover: '/ThinkingOutLoud.png',
        title: 'Thinking out Loud',
        artist: 'Ed Sheeran',
        album: 'x',
        time: '4:41',
        lyrics: []
    },
    {
        cover: '/Sorry.png',
        title: 'Sorry',
        artist: 'Justin Bieber',
        album: 'Purpose',
        time: '3:20',
        lyrics: []
    },
    {
        cover: '/CaliforniaGurls.png',
        title: 'California Gurls',
        artist: 'Katy Perry (feat. Snoop Dogg)',
        album: 'Teenage Dream',
        time: '3:54',
        lyrics: []
    },
    {
        cover: '/Dynamite.png',
        title: 'Dynamite',
        artist: 'Taio Cruz',
        album: 'Rokstarr',
        time: '3:23',
        lyrics: []
    },
];


